-- MySQL Script generated by MySQL Workbench
-- Thu 29 Aug 2019 01:51:39 PM EDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema DEG_Overlap_Analysis_System
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `DEG_Overlap_Analysis_System` ;

-- -----------------------------------------------------
-- Schema DEG_Overlap_Analysis_System
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DEG_Overlap_Analysis_System` DEFAULT CHARACTER SET utf8 ;
USE `DEG_Overlap_Analysis_System` ;

-- -----------------------------------------------------
-- Table `DEG_Overlap_Analysis_System`.`EXPERIMENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DEG_Overlap_Analysis_System`.`EXPERIMENT` ;

CREATE TABLE IF NOT EXISTS `DEG_Overlap_Analysis_System`.`EXPERIMENT` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'The unique internal identifier assigned to this experiment',
  `lab` VARCHAR(50) NOT NULL DEFAULT 'None' COMMENT 'The lab responsible for this experiment',
  `title` VARCHAR(2000) NOT NULL DEFAULT 'None' COMMENT 'The descriptive title of this experiment',
  `repository` VARCHAR(2000) NOT NULL DEFAULT 'None' COMMENT 'If this experiment is publically available, the repository from where it was retrived',
  `external_accession` VARCHAR(500) NOT NULL DEFAULT 'None' COMMENT 'The accession number assigned to this experiment by the repository that hosts it\n',
  `organism` VARCHAR(50) NOT NULL DEFAULT 'None' COMMENT 'The model organism that this experiment represents',
  `proc_method` VARCHAR(2000) NOT NULL DEFAULT 'None' COMMENT 'A description of the method used to process these samples',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DEG_Overlap_Analysis_System`.`SAMPLE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DEG_Overlap_Analysis_System`.`SAMPLE` ;

CREATE TABLE IF NOT EXISTS `DEG_Overlap_Analysis_System`.`SAMPLE` (
  `experiment_id` INT NOT NULL,
  `label` VARCHAR(500) NOT NULL COMMENT 'Within an experiment, the unique label for this sample',
  `external_accession` VARCHAR(50) NULL DEFAULT NULL COMMENT 'The external accession number assigned to this sample by a data repository (eg GEO, Array Express)',
  `short_name` VARCHAR(500) NULL DEFAULT NULL COMMENT 'Human readable label for this sample eg \"WT_0_Hr_1\"',
  `platform` VARCHAR(500) NULL DEFAULT NULL COMMENT 'The platform used to generate this data eg \"Affymetrix HG U133A\" or \"Illumina RNA-Seq\"',
  `proc_batch` INT NOT NULL DEFAULT 1 COMMENT 'The batch that this sample\'s data was processed / normalized with',
  PRIMARY KEY (`experiment_id`, `label`),
  INDEX `fk_SAMPLE_EXPERIMENT1_idx` (`experiment_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DEG_Overlap_Analysis_System`.`SAMPLE_CAT_ATR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DEG_Overlap_Analysis_System`.`SAMPLE_CAT_ATR` ;

CREATE TABLE IF NOT EXISTS `DEG_Overlap_Analysis_System`.`SAMPLE_CAT_ATR` (
  `experiment_id` INT NOT NULL,
  `sample_label` VARCHAR(500) NOT NULL,
  `attr_name` VARCHAR(50) NOT NULL COMMENT 'The name or label of this attribute eg \"Tissue\"',
  `attr_def` VARCHAR(2000) NULL COMMENT 'The long form definition of this attribute eg, \"The tissue from which this sample was collected\"',
  `attr_value` VARCHAR(500) NULL COMMENT 'The value of this attribute eg. \"Spleen\"',
  INDEX `fk_SAMPLE_CAT_ATR_SAMPLE1_idx` (`experiment_id` ASC, `sample_label` ASC),
  PRIMARY KEY (`experiment_id`, `sample_label`, `attr_name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DEG_Overlap_Analysis_System`.`GENE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DEG_Overlap_Analysis_System`.`GENE` ;

CREATE TABLE IF NOT EXISTS `DEG_Overlap_Analysis_System`.`GENE` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'The unique identifier of this gene for this system',
  `symbol` VARCHAR(50) NOT NULL COMMENT 'The official alphanumeric symbol of this gene',
  `external_id` VARCHAR(100) NULL COMMENT 'The external identifier used to locate this gene in an external database',
  `external_id_source` VARCHAR(100) NULL COMMENT 'The name external database where this external id corresponds to this gene',
  `description` VARCHAR(2000) NULL COMMENT 'The long form descriptive name of this gene. ',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DEG_Overlap_Analysis_System`.`GROUP`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DEG_Overlap_Analysis_System`.`GROUP` ;

CREATE TABLE IF NOT EXISTS `DEG_Overlap_Analysis_System`.`GROUP` (
  `experiment_id` INT NOT NULL,
  `label` VARCHAR(45) NOT NULL COMMENT 'The short label used to represent this group',
  `title` VARCHAR(2000) NULL DEFAULT NULL COMMENT 'The descriptive title of this group',
  `criteria` VARCHAR(2000) NULL DEFAULT NULL COMMENT 'The criteria used to assign samples to this group',
  PRIMARY KEY (`experiment_id`, `label`),
  INDEX `fk_GROUP_EXPERIMENT1_idx` (`experiment_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DEG_Overlap_Analysis_System`.`CONTRAST`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DEG_Overlap_Analysis_System`.`CONTRAST` ;

CREATE TABLE IF NOT EXISTS `DEG_Overlap_Analysis_System`.`CONTRAST` (
  `experiment_id` INT NOT NULL,
  `label` VARCHAR(50) NOT NULL COMMENT 'The short label used to reffer to this contrast',
  `title` VARCHAR(500) NULL DEFAULT NULL COMMENT 'The descriptive title of this contrast',
  `group_1_label` VARCHAR(45) NOT NULL,
  `group_2_label` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`experiment_id`, `label`),
  INDEX `fk_CONTRAST_GROUP1_idx` (`experiment_id` ASC, `group_1_label` ASC),
  INDEX `fk_CONTRAST_GROUP2_idx` (`experiment_id` ASC, `group_2_label` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DEG_Overlap_Analysis_System`.`PAIRWISE_RESULT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DEG_Overlap_Analysis_System`.`PAIRWISE_RESULT` ;

CREATE TABLE IF NOT EXISTS `DEG_Overlap_Analysis_System`.`PAIRWISE_RESULT` (
  `experiment_id` INT NOT NULL,
  `contrast_label` VARCHAR(50) NOT NULL,
  `gene_id` INT NOT NULL COMMENT 'The unique identifier of this gene, measured in this contrast',
  `group_1_avg` DECIMAL(16,6) NULL COMMENT 'The average abundance of this gene in samples from group 1 of this contrast',
  `group_2_avg` DECIMAL(16,6) NULL COMMENT 'The average abundance of this gene in samples from group 2 of this contrast',
  `logFC` DECIMAL(16,6) NULL COMMENT 'the log 2 fold change in abundance of this gene between groups 1 and 2 of this contrast',
  `p_value` DOUBLE NULL COMMENT 'The statistical significance of the difference in expression for this contrast',
  `fdr` DOUBLE NULL COMMENT 'The significance of this contrast after adjustment for multiple testing',
  INDEX `fk_PAIRWISE_RESULT_GENES1_idx` (`gene_id` ASC),
  PRIMARY KEY (`experiment_id`, `contrast_label`, `gene_id`),
  INDEX `fk_PAIRWISE_RESULT_CONTRAST1_idx` (`experiment_id` ASC, `contrast_label` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DEG_Overlap_Analysis_System`.`SAMPLE_NUM_ATR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DEG_Overlap_Analysis_System`.`SAMPLE_NUM_ATR` ;

CREATE TABLE IF NOT EXISTS `DEG_Overlap_Analysis_System`.`SAMPLE_NUM_ATR` (
  `experiment_id` INT NOT NULL,
  `sample_label` VARCHAR(500) NOT NULL,
  `attr_name` VARCHAR(50) NOT NULL COMMENT 'name ( or label ) of this attribute For example \"Weight\"',
  `attr_def` VARCHAR(2000) NULL COMMENT 'The long form definition of this attribute eg. \"The mouse\'s weight after fasting\"',
  `attr_units` VARCHAR(50) NULL COMMENT 'The units in which this attribute is measured eg \"grams\" or \"g\"',
  `attr_value` DECIMAL(16,6) NULL COMMENT 'The value of this attribute, eg \"32.5\"',
  PRIMARY KEY (`experiment_id`, `sample_label`, `attr_name`),
  INDEX `fk_SAMPLE_NUM_ATR_SAMPLE1_idx` (`experiment_id` ASC, `sample_label` ASC))
ENGINE = InnoDB
COMMENT = 'Numeric Attributes of a Sample';


-- -----------------------------------------------------
-- Table `DEG_Overlap_Analysis_System`.`GROUP_ASSIGN`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DEG_Overlap_Analysis_System`.`GROUP_ASSIGN` ;

CREATE TABLE IF NOT EXISTS `DEG_Overlap_Analysis_System`.`GROUP_ASSIGN` (
  `experiment_id` INT NOT NULL,
  `sample_label` VARCHAR(500) NOT NULL,
  `group_label` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`experiment_id`, `sample_label`, `group_label`),
  INDEX `fk_SAMPLE_has_GROUP_SAMPLE1_idx` (`experiment_id` ASC, `sample_label` ASC),
  INDEX `fk_SAMPLE_has_GROUP_GROUP1_idx` (`experiment_id` ASC, `group_label` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DEG_Overlap_Analysis_System`.`SAMPLE_MEASUREMENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DEG_Overlap_Analysis_System`.`SAMPLE_MEASUREMENT` ;

CREATE TABLE IF NOT EXISTS `DEG_Overlap_Analysis_System`.`SAMPLE_MEASUREMENT` (
  `experiment_id` INT NOT NULL COMMENT 'The unique id of the experiment where this gene was measured in this sample',
  `sample_label` VARCHAR(500) NOT NULL COMMENT 'The unique id of the sample in this experiment where this gene was measured',
  `gene_id` INT NOT NULL COMMENT 'The unique id of this gene measured in this sample from this experiment',
  `measurement` DECIMAL(16,6) NULL COMMENT 'The abundance measurement for this gene',
  `meas_type` VARCHAR(500) NULL COMMENT 'The type of mesaurement',
  PRIMARY KEY (`experiment_id`, `sample_label`, `gene_id`),
  INDEX `fk_RNASEQ_SAMPLE_COUNT_GENE1_idx` (`gene_id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
